# Puerto de ejecución (puedes cambiarlo si necesitas)
server.port=8080

# Configuración de base de datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Seguridad (por ahora permitir todo, se puede cambiar luego)
spring.security.user.name=admin
spring.security.user.password=admin
